### ISSUE TITLE
New book for quantum algorithms and QML

### ISSUE THREAD

**Issue by Scinawa** [poig/Qc_book_list#2]
Hello! 
I'd like to suggest this unitary.fund project: https://quantumalgorithms.org 
As suggested on slack by Tan Jun Liang, I checked the overlap with the other resources linked in the section Quantum Machine Learning, and there is no overlap (as most of the other resources are about python code or implementation, and this book is about theory and algorithms). 

Thank you!

**Comment by poig** [comment]
feel free to open a new issue or pull request for any suggestion change.
